// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "ChopBetter",
  description: "Generated by create next app",
};

// import "./globals.css";
// import { Poppins, Inter } from "next/font/google";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["600", "700"],
//   variable: "--font-poppins",
// });

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["400", "500"],
//   variable: "--font-inter",
// })

// export default function RootLayout({
//   children,
// }: {
//   children:React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={`${inter.variable} ${poppins.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
